let REACT_APP_MINIAPP_API_URL = '';
let REACT_APP_MINIAPP_ZP_URL = '';
let REACT_APP_MINIAPP_SPA_URL = '';
let REACT_APP_MINIAPP_BASE_URL = '';

export { REACT_APP_MINIAPP_API_URL, REACT_APP_MINIAPP_ZP_URL, REACT_APP_MINIAPP_SPA_URL, REACT_APP_MINIAPP_BASE_URL };
